jakob = {
    'Jakob',
    # 'Jachonia',
    # 'Jachonia',
    'Jacob',
    'Jacob',
    'Jacob)',
    'Jacob)',
    'Jacob,',
    'Jacob,',
    'Jacob.',
    'Jacob.',
    'Jacob:',
    'Jacob:',
    'Jacobi',
    'Jacobi',
    'Jacobs',
    'Jacobs',
    # 'Jacques',
    # 'Jacques',
    # 'Jadus',
    # 'Jadus',
    'Jakob',
    'Jakob,',
    'Jakob,',
    'Jakob.',
    'Jakob.',
    'Jakobi',
    'Jakobi',
    'Jakobs',
    'Jakobs',
    # 'Jama.',
    # 'Jama.',
    # 'Jason',
    # 'Jason',
    # 'Jehan',
    # 'Jehan',
    # 'Johannes',
    # 'Johannes',
    # 'Johannes,',
    # 'Johannes,',
    # 'Johanns',
    # 'Johanns',
    # 'Jonas',
    # 'Jonas',
    # 'Jonas.',
    # 'Jonas.',
    # 'Jonckbloet',
    # 'Jonckbloet',
    # 'Jormunrek',
    # 'Jormunrek',
    # 'Josaphat',
    # 'Josaphat',
    # 'Joseph',
    # 'Joseph',
    # 'Joseph.',
    # 'Joseph.',
    # 'Josephs',
    # 'Josephs'
}

wilhelm = {
    'Wilh.',
    'Wilh.',
    'Wilhelm!',
    'Wilhelm!',
    'Wilhelm',
    'Wilhelm',
    'Wilhelm,',
    'Wilhelm,',
    'Wilhelm.',
    'Wilhelm.',
    'Wilhelmchen!',
    'Wilhelmchen!',
    'Wilhelmlein!',
    'Wilhelmlein!',
    'Wilhelms',
    'Wilhelms'
}
